version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gulp-replace
    versions:
    - 1.0.0
    - 1.1.1
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
    - 10.7.1
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
    - 2.0.0
    - 2.0.1
  - dependency-name: chalk
    versions:
    - 4.1.0
